### ISSUE TITLE
Missing link to documentation

### ISSUE THREAD

**Issue by tjorim** [samuelspagl/ha_samsung_soundbar#18]
I noticed there is no link to [the documentation](https://ha-samsung-soundbar.vercel.app/) in the README.
I still had my api_key and device_id laying around, but first time users might not.
Also care to explain the max_volume setting? Not all soundsbars can go to 100%? (also see #7)

**Comment by samuelspagl** [comment]
Yeah the README can definitely use a little love. 😄 

The `max_volume` setting is basically a limiter. My soundbar is already incredible loud on the value 30, and I really don't wanna try the 100 😅 . Therefore this setting readjusts the media_player slider (which goes from 0 to 1, and in the UI from 0-100) not to scale to 100 but to the value of `max_volume`.

**Comment by tjorim** [comment]
I agree with that, haven't put mine above 20 since I had it, usually it's just around 10. But I still set the max_volume for this integration to 100 because otherwise HA won't match what the TV/soundbar shows. Btw, do you have any links for a small donation (like 'buy me a coffee')?

**Comment by samuelspagl** [comment]
Yeah that really is a struggle. I would also be open to give two options in the configuration of the device.
1. current solution, apply scaling based on the `max_volume` to the `media_player` instance
2. use `max_volume` as a hard limit, so even if somebody would try to set it to `60` or so, that it would only apply the max amount of `max_volume`

**Comment by samuelspagl** [comment]
> Btw, do you have any links for a small donation (like 'buy me a coffee')?

There should be a ko-fi link linked to this repository

**Comment by tjorim** [comment]
That would also be a neat solution but in my opinion it's not the responsibility of an integration. I didn't see the link earlier (on mobile) but found it now.

**Comment by samuelspagl** [comment]
Thanks a lot! Wouldn't have been nescessary tho :). I'm just happy that other people can use the integration.

**Comment by samuelspagl** [comment]
@tjorim I created a new PR for the documentation changes. If you have time, take a look at it. I'll try to make things as clear as possible :)
