### ISSUE TITLE
Specify license

### ISSUE THREAD

**Issue by K900** [samuelspagl/ha_samsung_soundbar#31]
Hi! Could you please specify a license for the source code of this repo? I want to package it for a distribution, but right now I'm legally not allowed to.

**Comment by samuelspagl** [comment]
Would you just like to create a Pypi package from it?
Then you could also add a PR here and we publish it directly from this repo. 

I also thought about doing it at some point, and switching from pipenv to poetry (as it also has packaging functionality).

**Comment by K900** [comment]
The distribution I'm interested in is NixOS/nixpkgs, we can get the sources directly from Github, but we can't actually distribute the package without a license.

**Comment by samuelspagl** [comment]
Okay, I'll add a license later. Dunno if I get to do it this evening, but at latest tomorrow.

Dunno if it makes sense to include it into this repository 🤷🏻‍♂️, but feel free to open a PR, if you think that its good packaging it from this repository :)

**Comment by samuelspagl** [comment]
I added a MIT licence :) That should be sufficient for your usecase right? :)

**Comment by K900** [comment]
Yes, thank you!

**Comment by samuelspagl** [comment]
Nice :). If you are interested I would list your distribution in the README.

But no pressure ^-^

**Comment by K900** [comment]
Sure. For NixOS users, the config will look something like

```nix
services.home-assistant.customComponents = [ pkgs.home-assistant-custom-components.yassi ];
```
