### ISSUE TITLE
Not asking variables

### ISSUE THREAD

**Issue by PimStevens** [samuelspagl/ha_samsung_soundbar#37]
Hi, in your readme i can read: 'To integrate your Samsung Soundbar with Home Assistant using YASSI, you will be asked for the following variables'. But my HA does not ask for these variables. What am i doing wrong? What lines i have to put into my configuration.yaml?

Best Regards,
Pim

**Comment by samuelspagl** [comment]
Currently the preferred way of using the Integration is through the web interface of HomeAssistant. 

When adding the integration through the "Devices" Tab, you should be prompted with a form to input your settings.

Which version are you using?

**Comment by PimStevens** [comment]
Thnx for your quick reply. I'm using 2024.6.4 and i used HACS to install the integration.

**Comment by PimStevens** [comment]
Hi, i tried it again (uninstalling, re-installing) and now it works!

Thnx!!

Pim

**Comment by samuelspagl** [comment]
Happy to hear that :) 
Have fun with the integration ✌️

**Comment by PimStevens** [comment]
Thnx!!

 

Van: Samuel Spagl ***@***.***> 
Verzonden: zaterdag 29 juni 2024 07:54
Aan: samuelspagl/ha_samsung_soundbar ***@***.***>
CC: PimStevens ***@***.***>; Author ***@***.***>
Onderwerp: Re: [samuelspagl/ha_samsung_soundbar] Not asking variables (Issue #37)

 

Happy to hear that :)
Have fun with the integration ✌️
