### ISSUE TITLE
Failed to setup

### ISSUE THREAD

**Issue by Bozrom** [samuelspagl/ha_samsung_soundbar#38]
Hi, I am having a problem getting this to work with my Samsung HW-Q990B. I have the Smarthings Soundbar installed and working however it only gives me an on off switch. Do I need to remove that before installing your integration, could that be the cause of my issue.
I get the following when I check the integration.

![image](https://github.com/samuelspagl/ha_samsung_soundbar/assets/173906313/f9add0f2-bcad-49a4-b352-4e1be43c9fc3)

My home assistant version is (please see below) and i'm running on raspberry pi v4.

![image](https://github.com/samuelspagl/ha_samsung_soundbar/assets/173906313/91a730b2-5011-4179-9163-330c6275d218)

Here is the log of the error.

Logger: homeassistant.config_entries
Source: config_entries.py:594
First occurred: 1 July 2024 at 09:47:43 (1 occurrences)
Last logged: 1 July 2024 at 09:47:43

Error setting up entry samsung_soundbar for samsung_soundbar

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/samsung_soundbar/__init__.py", line 69, in async_setup_entry
    await soundbar_device.update()
  File "/config/custom_components/samsung_soundbar/api_extension/SoundbarDevice.py", line 66, in update
    await self._update_soundmode()
  File "/config/custom_components/samsung_soundbar/api_extension/SoundbarDevice.py", line 91, in _update_soundmode
    payload = await self.get_execute_status()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/samsung_soundbar/api_extension/SoundbarDevice.py", line 454, in get_execute_status
    return dict_stuff["data"]["value"]["payload"]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

Any assistance you could offer would be gratefully recieved.
Many thanks in advance 
Cheers Brian

**Comment by samuelspagl** [comment]
Hi there ✌️,

So the error you See is quite Common currently. 

Can you reconfigure your soundbar Integration (three docs and "reconfigure") and uncheck all "extra" Features / entities. 

Even though your Soundbar Supports it, Samsungs API Changed and currently I cant retrieve the values, which is why you receive this error. 

You can still set everything through the custom services I created. 

If you want more information, you can read more in the Readme or other previous tickets 😊

**Comment by Bozrom** [comment]
That worked thank you.
