### ISSUE TITLE
TV ARC /EARC input isn't avaliable

### ISSUE THREAD

**Issue by chrissi323** [samuelspagl/ha_samsung_soundbar#46]
I have a Samsung Q995D soundbar. The YASSI integration overall works very well but it is missing the option to select TV ARC/EARC as input. Is this a limitation of the Smartthings API? I noticed that the input_preset changes to "digital" if I select TV ARC/EARC via the Smartthings App.

Setting the input_preset to "digital" via Home Assistant selects the optical input, so there is no way to make sure that the EARC channel is used.

This is a minor issue as most of the times the soundbar selects the correct input by itself but I have had occasions where it didn't. In this case I can't recover from Home Assistant, I have to fetch the remote.

**Comment by samuelspagl** [comment]
Hi @chrissi323,

the inputs listed in the `media_player` instance are coming directly form the SmartThings API. I receive the possible Inputs as well as the currently selected one. Therefore yes it is a limitation of the SmartThings API from my point of view. 

Hope that helps!

**Comment by samuelspagl** [comment]
I'll close this ticket as there is no additional reaction anymore :) 

Feel free to reopen if necessary.

**Comment by chrissi323** [comment]
Hi,

 

sorry… life got in the way….

 

I messed around with the API on my own and couldn’t find any way around this either. They simply don’t have that input although it’s selectable in the Smartthings app.

 

I’d prefer a local solution anyways. It seems there was something with older smartspeakers from Samsung but I couldn’t get it to work with the Q995D.

 

Thanks for your integration!

 

Christian

 

 

Von: Samuel Spagl ***@***.***> 
Gesendet: Dienstag, 17. Dezember 2024 09:42
An: samuelspagl/ha_samsung_soundbar ***@***.***>
Cc: chrissi323 ***@***.***>; Mention ***@***.***>
Betreff: Re: [samuelspagl/ha_samsung_soundbar] TV ARC /EARC input isn't avaliable (Issue #46)

 

I'll close this ticket as there is no additional reaction anymore :)

Feel free to reopen if necessary.
