### ISSUE TITLE
Unable to control volume

### ISSUE THREAD

**Issue by tintin814** [samuelspagl/ha_samsung_soundbar#7]
I am unable to control the volume through this integration.  In the attribute, it shows "volume_level: 1" while the slider is set at the maximum. Once I slide it at bit left the soundbar will become mute. It seems the volume is not configured correctly.  Should I set the maximum volume level manually in the yaml?

**Comment by samuelspagl** [comment]
I check it this evening and come back to you :)

**Comment by tintin814** [comment]
I finally resolved this by re-adding the device and input the max volume during configuration.  It seems the integration doesn't get the volume attribute correctly if max volume is left blank.

**Comment by samuelspagl** [comment]
@tintin814 did you add the device via the UI or `yaml`?

**Comment by samuelspagl** [comment]
This issue is stale for nearly 7 weeks now, therefore I will close it.

If there's still something not working as expected feel free to reopen the issue.
